In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,34,67,88])
print(arr)

In [ ]:
arr.shape

In [ ]:
arr.dtype

In [ ]:
arr.size

In [ ]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])


In [ ]:
arr

In [ ]:
arr.shape

In [ ]:
a=[ [1]*3]*3

In [ ]:
a

In [2]:
import numpy as np
print('Enter the input :')
x=[int(x) for x in input().split()]
x=np.array(x)
print(x.dtype)
x.reshape(3,3)

Enter the input :
1 2 3 4 5 6 7 8 9
int32


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
import numpy as np
x = np.array([1,2,3])
y = np.array([3,2,1])


In [4]:
x+y

array([4, 4, 4])

In [5]:
x-y

array([-2,  0,  2])

In [6]:
x*y

array([3, 4, 3])

In [7]:
x/y

array([0.33333333, 1.        , 3.        ])

In [8]:
np.linspace(1,20,200)

array([ 1.        ,  1.09547739,  1.19095477,  1.28643216,  1.38190955,
        1.47738693,  1.57286432,  1.66834171,  1.7638191 ,  1.85929648,
        1.95477387,  2.05025126,  2.14572864,  2.24120603,  2.33668342,
        2.4321608 ,  2.52763819,  2.62311558,  2.71859296,  2.81407035,
        2.90954774,  3.00502513,  3.10050251,  3.1959799 ,  3.29145729,
        3.38693467,  3.48241206,  3.57788945,  3.67336683,  3.76884422,
        3.86432161,  3.95979899,  4.05527638,  4.15075377,  4.24623116,
        4.34170854,  4.43718593,  4.53266332,  4.6281407 ,  4.72361809,
        4.81909548,  4.91457286,  5.01005025,  5.10552764,  5.20100503,
        5.29648241,  5.3919598 ,  5.48743719,  5.58291457,  5.67839196,
        5.77386935,  5.86934673,  5.96482412,  6.06030151,  6.15577889,
        6.25125628,  6.34673367,  6.44221106,  6.53768844,  6.63316583,
        6.72864322,  6.8241206 ,  6.91959799,  7.01507538,  7.11055276,
        7.20603015,  7.30150754,  7.39698492,  7.49246231,  7.58

In [9]:
np.random.random((3,3))

array([[0.8501967 , 0.3754018 , 0.65551762],
       [0.14826205, 0.27069462, 0.47227205],
       [0.90893105, 0.97558972, 0.30295351]])

In [10]:
np.random.random((3,3,4))

array([[[9.66935150e-02, 6.92520539e-01, 3.67426456e-01, 4.38958401e-01],
        [6.48002478e-02, 8.81993392e-01, 8.18254025e-01, 1.61021446e-01],
        [4.27474497e-01, 1.21167959e-02, 1.50743604e-01, 2.88898087e-01]],

       [[7.35313254e-01, 1.81839372e-01, 7.61112240e-02, 8.77121298e-01],
        [1.78419559e-01, 3.56871267e-02, 7.39810062e-01, 1.82231128e-01],
        [9.41964339e-01, 2.50215215e-02, 8.75239594e-01, 6.54812463e-01]],

       [[2.69138742e-01, 7.06205764e-01, 5.45207024e-02, 4.61147931e-01],
        [4.73248579e-01, 2.82511294e-01, 2.41344867e-01, 5.07069793e-02],
        [9.42357628e-01, 3.16731119e-04, 2.46468824e-01, 6.32006275e-01]]])

In [12]:
np.arange(1,10,.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [16]:
a=np.array([[1,2],[3,4]])
b=np.array([[23,45],[45,90]])


In [17]:
np.vstack([a,b])

array([[ 1,  2],
       [ 3,  4],
       [23, 45],
       [45, 90]])

In [18]:
np.hstack([a,b])

array([[ 1,  2, 23, 45],
       [ 3,  4, 45, 90]])

In [19]:
np.dstack([a,b])

array([[[ 1, 23],
        [ 2, 45]],

       [[ 3, 45],
        [ 4, 90]]])

In [20]:
np.vstack([a,b]).shape

(4, 2)

In [23]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
np.matrix(range(1,10)).reshape(3,3)

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [29]:
np.random.random((1,1000))


array([[0.84998799, 0.00630289, 0.0409256 , 0.13292768, 0.68352199,
        0.5383185 , 0.97285849, 0.02990929, 0.58179734, 0.05313309,
        0.31036623, 0.22368996, 0.88661202, 0.45687255, 0.13999319,
        0.12747995, 0.72250386, 0.35253877, 0.90197148, 0.20264512,
        0.36822371, 0.26997358, 0.99579711, 0.18201115, 0.17294022,
        0.15905157, 0.34806927, 0.68099109, 0.40440919, 0.62074799,
        0.28326741, 0.36333579, 0.59150089, 0.82346594, 0.09991154,
        0.55304885, 0.20543045, 0.50624729, 0.64981398, 0.367503  ,
        0.67223716, 0.18379141, 0.07202362, 0.88540064, 0.86783855,
        0.75392065, 0.74760397, 0.20482109, 0.66294432, 0.51581317,
        0.67799245, 0.13417991, 0.37396639, 0.37242738, 0.15521738,
        0.33868219, 0.44947538, 0.73413119, 0.56402379, 0.00793752,
        0.99183657, 0.85605717, 0.48303937, 0.17734173, 0.46355512,
        0.72226259, 0.75198521, 0.1908608 , 0.28379231, 0.44038874,
        0.61334972, 0.43171033, 0.60117764, 0.90

In [30]:
print(np.mean)

<function mean at 0x00000243ACD768C8>


In [32]:
x=np.matrix(range(1,1000))

matrix([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
          14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
          27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
          40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
          53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
          66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
          79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
          92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
         105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
         118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
         131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
         144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
         157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
         170, 171, 172, 173, 174, 175,

In [36]:
print(np.mean(x))

2.0
